config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  resources :sys_users
  resources :sys_roles

  get 'home', :to => 'home#index', :as => 'home'
  get 'sessions/login', :to => 'sessions#login', :as => 'login'
  post 'sessions/login_validate', :to => 'sessions#validate', :as => 'login_validate'
  get 'sessions/logout', :to => 'sessions#logout', :as => 'logout'

end

app/models/sys_role.rb
class SysRole < ActiveRecord::Base

  validates_uniqueness_of :roleName, {:message => '角色名称已存在！'}
  validates_presence_of :roleName, :message => '角色名称必填'

end

app/models/sys_user.rb
class SysUser < ActiveRecord::Base

  has_many :sys_user_roles
  has_many :sys_roles, :through => :sys_user_roles

  validates_uniqueness_of :name, {:allow_nil => true, :message => '用户名已存在！'}
  validates_length_of :pwd, {:allow_nil => true, :minimum => 6, :message => '密码最小长度为6位'}
  validates_presence_of :sex, :message => '性别不能为空'

  #联系方式屏蔽部分字符
  def phone_str
    return "" if self.phone.blank? || self.phone.length < 11
    str = self.phone
    str[3]=str[4]=str[5]=str[6]="*"
    return str
  end

  def password
    @password
  end

  def password=(pass)
    return unless pass
    @password = pass
    gennerate_password(pass)      
  end

  #角色名称条
  def role_desc
    return "" unless self.sys_roles
    roleNames = []
    self.sys_roles.each do |role|
      roleNames.push role.roleName
    end
    return roleNames.join(',')
  end

  #登录验证
  def self.authenticate(name,password)
    user = SysUser.find_by(:name => name)
    if user && Digest::SHA256.hexdigest(password + user.hashcode) == user.pwd
      return user
    else
      return nil
    end
  end

  private
  #密码生成
  def gennerate_password(pass)
    salt = Array.new(12){rand(2048).to_s(36)}.join
    self.hashcode, self.pwd = salt, Digest::SHA256.hexdigest(pass + salt)
  end
end

app/models/sys_user_role.rb
class SysUserRole < ActiveRecord::Base
  belongs_to :sys_user
  belongs_to :sys_role

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :set_current_user, :except => [:login,:validate]
  protected
  def set_current_user
    if !session[:user_name]
      redirect_to login_path
    end

  end 
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	layout "main"

	def index
	end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :validate_params, :only => [:validate]

  #登录页面
  def login
  end

  #登录验证
  def validate
    if(flash[:errormsg])
      redirect_to login_path
    end
    @user = SysUser.authenticate(params[:name], params[:password])
    if @user
      session[:user_name] = @user.name
      session[:user_email] = @user.email
      flash[:notice] = "#{@user.name}，欢迎您！TIME: #{DateTime.parse(Time.now.to_s).strftime('%Y-%m-%d %H:%M:%S').to_s}"
      redirect_to home_path
    else
      flash[:errormsg] = "用户名或密码错误!"
      redirect_to login_path
    end
  end

  #登出
  def logout
    session[:user_name] = nil
    session[:user_email] = nil
    redirect_to login_path
  end

private
  #参数验证
  def validate_params
    if !params[:name]
      flash[:errormsg] = "用户名不能为空"
    elsif !params[:password]
      flash[:errormsg] = "密码不能为空"
    else
    end
  end

end

app/controllers/sys_roles_controller.rb
class SysRolesController < ApplicationController

  before_action :set_sys_role, only: [:show, :edit, :update, :destroy]

  layout  "main"

  #前往列表页
  def index
    if params[:search] != ''
      @sys_roles = SysRole.where("roleName LIKE '%#{params[:search]}%'")
        .paginate(:page => params[:page] || 1, :per_page => 5)
    else
      @sys_roles = SysRole.paginate(:page => params[:page] || 1, :per_page => 5)
    end
  end

  #前往新增页
  def new
    @sys_role = SysRole.new
  end

  #新增
  def create
    @sys_role = SysRole.new(sys_role_params)
    #保存
    if @sys_role.save
      redirect_to sys_roles_url
    else
      render :new
    end
  end

  #前往修改
  def edit
  end

  #修改
  def update
    if @sys_role.update(sys_role_params)
      redirect_to sys_roles_url
    else
      render :edit
    end
  end

  #删除
  def destroy
    @sys_role.destroy
    redirect_to sys_roles_url
  end


  private
    def set_sys_role
      @sys_role = SysRole.find(params[:id])
    end

    def sys_role_params
      params.require(:sys_role).permit(:roleName, :remark)
    end

end

app/controllers/sys_users_controller.rb
class SysUsersController < ApplicationController
  before_action :set_sys_user, only: [:show, :edit, :update, :destroy]
  layout  "main"

  # GET /sys_users
  def index
    #@sys_users = SysUser.search(params[:search]).paginate(:page => params[:page], :per_page => 5)
    if params[:search] != ''
      @sys_users = SysUser.where("name LIKE '%#{params[:search]}%'")
        .paginate(:page => params[:page] || 1, :per_page => 5)
    else
      @sys_users = SysUser.paginate(:page => params[:page] || 1, :per_page => 5)
    end
  end

  # GET /sys_users/1
  def show
  end

  # GET /sys_users/new
  def new
    @sys_user = SysUser.new
  end

  # GET /sys_users/1/edit
  def edit
  end

  # POST /sys_users
  def create
    @sys_user = SysUser.new(sys_user_params)
    
    #保存
    if @sys_user.save

      #获取所有的角色关联，并删除
      user_roles = SysUserRole.find_by(:sys_user => @sys_user)
      if !user_roles.nil?
        if user_roles.class == SysUserRole
          user_roles.destroy
        else
          user_roles.each do |user_role|
            user_role.destroy
          end
        end
      end

      #添加角色关联
      role_ids = params[:sys_user][:sys_role_ids]
      if role_ids
        role_ids.each do |role_id|
          if !role_id.nil? &&!role_id.empty?
            SysUserRole.create :sys_user => @sys_user,
              :sys_role => SysRole.new(:id => role_id)
          end
        end
      end

      redirect_to sys_users_url
    else
      render :new
    end
  end

  # PATCH/PUT /sys_users/1
  def update
    if @sys_user.update(sys_user_params)
      #获取所有的角色关联，并删除
      user_roles = SysUserRole.find_by(:sys_user => @sys_user)
      if !user_roles.nil?
        if user_roles.class == SysUserRole
          user_roles.destroy
        else
          user_roles.each do |user_role|
            user_role.destroy
          end
        end
      end

      #添加角色关联
      role_ids = params[:sys_user][:sys_role_ids]
      if role_ids
        role_ids.each do |role_id|
          if !role_id.nil? &&!role_id.empty?
            SysUserRole.create :sys_user => @sys_user,
              :sys_role => SysRole.new(:id => role_id)
          end
        end
      end


      redirect_to sys_users_url
    else
      render :edit
    end
  end

  # DELETE /sys_users/1
  def destroy
    @sys_user.destroy
    redirect_to sys_users_url
  end

  private
    def set_sys_user
      @sys_user = SysUser.find(params[:id])
    end

    def sys_user_params
      params.require(:sys_user).permit(:name, :password, :photo, :phone, :sex, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
 
end

app/helpers/sys_roles_helper.rb
module SysRolesHelper
end

app/helpers/sys_users_helper.rb
module SysUsersHelper
end

app/views/home/index.html.erb
  <header class="header bg-white b-b b-light">
    <p><%= flash[:notice]%></p>
  </header>
  <section class="scrollable wrapper w-f">
    <p class="h4">这是首页...</p>
  </section>
  

app/views/layouts/_content_footer.html.erb
<footer class="footer bg-white b-t b-light">
  <p>This is a footer</p>
</footer>

app/views/layouts/_header.html.erb
<header class="bg-primary header header-md navbar navbar-fixed-top-xs box-shadow">
      <div class="navbar-header aside-md dk">
        <a class="btn btn-link visible-xs" data-toggle="class:nav-off-screen,open" data-target="#nav,html">
          <i class="fa fa-bars"></i>
        </a>
        <a href="<%= root_path %>" class="navbar-brand">
          <%= image_tag "logo.png", class: "m-r-sm", alt: "scale"%>
          <span class="hidden-nav-xs">后台管理系统</span>
        </a>
        <a class="btn btn-link visible-xs" data-toggle="dropdown" data-target=".user">
          <i class="fa fa-cog"></i>
        </a>
      </div>
      <ul class="nav navbar-nav hidden-xs">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            <i class="i i-grid"></i>
          </a>
          <section class="dropdown-menu aside-lg bg-white on animated fadeInLeft">
            <div class="row m-l-none m-r-none m-t m-b text-center">
              <div class="col-xs-4">
                <div class="padder-v">
                  <a href="#">
                    <span class="m-b-xs block">
                      <i class="i i-mail i-2x text-primary-lt"></i>
                    </span>
                    <small class="text-muted">邮箱</small>
                  </a>
                </div>
              </div>
              <div class="col-xs-4">
                <div class="padder-v">
                  <a href="#">
                    <span class="m-b-xs block">
                      <i class="i i-calendar i-2x text-danger-lt"></i>
                    </span>
                    <small class="text-muted">日历</small>
                  </a>
                </div>
              </div>
              <div class="col-xs-4">
                <div class="padder-v">
                  <a href="#">
                    <span class="m-b-xs block">
                      <i class="i i-map i-2x text-success-lt"></i>
                    </span>
                    <small class="text-muted">地图</small>
                  </a>
                </div>
              </div>
              <div class="col-xs-4">
                <div class="padder-v">
                  <a href="#">
                    <span class="m-b-xs block">
                      <i class="i i-paperplane i-2x text-info-lt"></i>
                    </span>
                    <small class="text-muted">训练</small>
                  </a>
                </div>
              </div>
              <div class="col-xs-4">
                <div class="padder-v">
                  <a href="#">
                    <span class="m-b-xs block">
                      <i class="i i-images i-2x text-muted"></i>
                    </span>
                    <small class="text-muted">照片</small>
                  </a>
                </div>
              </div>
              <div class="col-xs-4">
                <div class="padder-v">
                  <a href="#">
                    <span class="m-b-xs block">
                      <i class="i i-clock i-2x text-warning-lter"></i>
                    </span>
                    <small class="text-muted">时间</small>
                  </a>
                </div>
              </div>
            </div>
          </section>
        </li>
      </ul>
      <form class="navbar-form navbar-left input-s-lg m-t m-l-n-xs hidden-xs" role="search">
        <div class="form-group">
          <div class="input-group">
            <span class="input-group-btn">
              <button type="submit" class="btn btn-sm bg-white b-white btn-icon"><i class="fa fa-search"></i></button>
            </span>
            <input type="text" class="form-control input-sm no-border" placeholder="Search apps, projects...">            
          </div>
        </div>
      </form>
      
      <ul class="nav navbar-nav navbar-right m-n hidden-xs nav-user user">
        <!-- <li class="hidden-xs">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            <i class="i i-chat3"></i>
            <span class="badge badge-sm up bg-danger count">2</span>
          </a>
          <section class="dropdown-menu aside-xl animated flipInY">
            <section class="panel bg-white">
              <div class="panel-heading b-light bg-light">
                <strong>You have <span class="count">2</span> notifications</strong>
              </div>
              <div class="list-group list-group-alt">
                <a href="#" class="media list-group-item">
                  <span class="pull-left thumb-sm">
                    <%= image_tag "a0.png",class: "img-circle",alt: "..."%>
                  </span>
                  <span class="media-body block m-b-none">
                    Use awesome animate.css<br>
                    <small class="text-muted">10 minutes ago</small>
                  </span>
                </a>
                <a href="#" class="media list-group-item">
                  <span class="media-body block m-b-none">
                    1.0 initial released<br>
                    <small class="text-muted">1 hour ago</small>
                  </span>
                </a>
              </div>
              <div class="panel-footer text-sm">
                <a href="#" class="pull-right"><i class="fa fa-cog"></i></a>
                <a href="#notes" data-toggle="class:show animated fadeInRight">See all the notifications</a>
              </div>
            </section>
          </section>
        </li> -->

        <!-- <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            <span class="thumb-sm avatar pull-left">
              <%= image_tag "a0.png",alt: "..."%>
            </span>
            <%=session[:user_name]%> <b class="caret"></b>
          </a>
          <ul class="dropdown-menu animated fadeInRight">            
            <li>
              <span class="arrow top"></span>
              <a href="#">设置</a>
            </li>
            <li>
              <a href="profile.html">个人资料</a>
            </li>
            <li>
              <a href="#">
                <span class="badge bg-danger pull-right">3</span>通知
              </a>
            </li>
            <li>
              <a href="#">帮助</a>
            </li>
            <li class="divider"></li>
            <li>
              <a href="<%= logout_path%>" data-toggle="ajaxModal" >退出</a>
            </li>
          </ul>
        </li> -->
      </ul>      
    </header>

app/views/layouts/_left_footer.html.erb
<footer class="footer hidden-xs no-padder text-center-nav-xs">
  <a href="modal.lockme.html" data-toggle="ajaxModal" class="btn btn-icon icon-muted btn-inactive pull-right m-l-xs m-r-xs hidden-nav-xs">
    <i class="i i-logout"></i>
  </a>
  <a href="#nav" data-toggle="class:nav-xs" class="btn btn-icon icon-muted btn-inactive m-l-xs m-r-xs">
    <i class="i i-circleleft text"></i>
    <i class="i i-circleright text-active"></i>
  </a>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>App</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/home.html.erb
<!DOCTYPE html>
<html lang="en" class="app js no-touch no-android chrome no-firefox no-iemobile no-ie no-ie8 no-ie10 no-ie11 no-ios">
<head>

  <title>App</title>
  <meta charset="utf-8" />
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <!--[if lt IE 9]>
    <script src="<%= asset_path 'ie/html5shiv.js'%>"></script>
    <script src="<%= asset_path 'ie/respond.min.js' %>"></script>
    <script src="<%= asset_path 'ie/excanvas.js' %>"></script>
  <![endif]-->
  <%= csrf_meta_tags %>
</head>
<body>
	<section class="vbox">
		<%= render "layouts/header"%>
		<section>
			<section class="hbox stretch">
			<%= render "layouts/left" %>
        <section id="content">
          <section class="vbox">
            <%= yield %>
            <%= render "layouts/content_footer" %>
          </section>
          <a href="#" class="hide nav-off-screen-block" data-toggle="class:nav-off-screen" data-target="#nav"></a>
        </section>
			</section>
		</section>
	</section>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
</body>
</html>

app/views/layouts/main.html.erb
<!DOCTYPE html>
<html lang="en" class="app js no-touch no-android chrome no-firefox no-iemobile no-ie no-ie8 no-ie10 no-ie11 no-ios">
<head>

  <title>App</title>
  <meta charset="utf-8" />
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <!--[if lt IE 9]>
    <script src="<%= asset_path 'ie/html5shiv.js'%>"></script>
    <script src="<%= asset_path 'ie/respond.min.js' %>"></script>
    <script src="<%= asset_path 'ie/excanvas.js' %>"></script>
  <![endif]-->
  <%= csrf_meta_tags %>
</head>
<body>
	<section class="vbox">
		<%= render "layouts/header"%>
		<section>
			<section class="hbox stretch">
			<%= render "layouts/left" %>
        <section id="content">
          <section class="vbox">
            <section class="scrollable padder">
            <%= yield %>
            </section>
            <%= render "layouts/content_footer" %>
          </section>
          <a href="#" class="hide nav-off-screen-block" data-toggle="class:nav-off-screen" data-target="#nav"></a>
        </section>
			</section>
		</section>
	</section>
 
</body>
</html>

app/views/sys_roles/_form.html.erb
<%= simple_form_for(@sys_role, :defaults => {:required => false}, 
  html: {id: "sys_role_form",class: "form-horizontal"},
  data: {validate: "parsley"}) do |f| %>

  <section class="panel panel-default">

    <% if @sys_role.errors.any? %>
      <div class="alert alert-danger">
        <button type="button" class="close" data-dismiss="alert">×</button>
        <i class="fa fa-ban-circle"></i>
        <strong>
        有<%= @sys_role.errors.count %>条错误消息：
        </strong>
        <ul>
        <% @sys_role.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <header class="panel-heading">
      <strong>角色信息</strong>
    </header>

    <div class="panel-body">
      <div class="form-group">
        <%=f.label :roleName, :required => true, :class => "col-sm-3 control-label"%>
        <div class="col-sm-9">
          <%= f.text_field :roleName,
            :class => "input-sm input-s form-control parsley-validated", 
            "data-parsley-length" => "[1,50]" %> 
        </div>
      </div>

      <div class="form-group">
        <%=f.label :remark, :class => "col-sm-3 control-label"%>
        <div class="col-sm-9">
          <%= f.text_area :remark, :class => "form-control parsley-validated",
            :style => "width:300px;height:120px;",
            "data-parsley-length" => "[0,255]"%>
        </div>
      </div>

      <br/>
      <div class="form-group">
        <label class="col-sm-3"></label>
        <div class="col-sm-9">
          <%= f.button :submit, :class => "btn btn-primary", :value=> "保 存"%>&nbsp;&nbsp;&nbsp;&nbsp;
          <%= button_tag "返回", :type => 'button', :class => "btn btn-default",'onclick' => "history.go(-1)" %>
        </div>
      </div>
    </div>

    <!-- <footer class="panel-footer text-right bg-light lter"></footer> -->
  </section>

<% end %>
<script type="text/javascript">
    $('#sys_role_form').parsley();  
</script>

app/views/sys_roles/edit.html.erb
<div class="m-b-md">
  <h3 class="m-b-none">修改角色</h3>
</div>
 
</div><%= render 'form' %>

app/views/sys_roles/index.html.erb
<section class="panel panel-default">
    <header class="panel-heading">
      角色管理
    </header>

    <div class="row wrapper">
      <div class="col-sm-5 m-b-xs">
        <%= link_to raw('<i class="fa fa-plus"></i> 添加'), new_sys_role_path, :class => 'btn btn-sm btn-default' %>
      </div>
      <div class="col-sm-4 m-b-xs">
      </div>
      <div class="col-sm-3">
        <%= form_tag sys_roles_path,:method => 'get' do -%>
          <div class="input-group">
              <%= text_field_tag :search, params[:search], :class => "input-sm form-control", :placeholder => "Search" -%>
              <span class="input-group-btn">
                <%= submit_tag "Go!", :name => nil, :class => "btn btn-sm btn-default" %>
              </span>
          </div>
        <% end %>
      </div>
    </div>

    <div class="table-responsive">
        <table class="table table-striped b-t b-light">
          <thead>
            <tr>
              <th width="120">角色名称</th>
              <th>备注</th>
              <th width="120">操作</th> 
            </tr>
          </thead>
          <tbody>
            <% @sys_roles.each do |role| %>
              <tr>
                <td><%= role.roleName %></td>
                <td><%= role.remark %></td>
                <td>
                  <div class="btn-group btn-group-sm">
                    <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
                      操 作 <span class="caret"></span>
                    </button>
                    <ul class="dropdown-menu" role="menu">
                      <li><%= link_to raw('<i class="fa fa-pencil-square"></i> 修 改'),edit_sys_role_path(role) %>
                      </li>
                      <li>
                      <%= link_to raw('<i class="fa fa-minus-circle"></i> 删 除'), role, method: :delete, data: { confirm: 'Are you sure?' } %>
                      
                      </li>
                    </ul>
                  </div>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>

        <footer class="panel-footer">
          <div class="row">
            <div style="float:left;padding-left:10px;">
              <%= will_paginate @sys_roles,
              :page_links => true,
              :inner_window => 6,
              :outer_window => 1,
              :previous_label => '上一页',
              :next_label => '下一页'
              %>
            </div>
            <div style="float:right;padding-right:10px;height:60px;line-height:60px;">
              共找到<%= @sys_roles.total_entries %>条记录, 共<%= @sys_roles.total_pages %>页
            </div>
          </div>
        </footer>
    </div>
</section>
<br />

app/views/sys_roles/new.html.erb
<div class="m-b-md">
  <h3 class="m-b-none">添加角色</h3>
</div>

 <%= render 'form' %>

app/views/sys_users/_form.html.erb
<%= simple_form_for(@sys_user, :defaults => {:required => false}, 
  html: {id: "sys_user_form",class: "form-horizontal"},
  data: {validate: "parsley"}) do |f| %>

<% if @sys_user.errors.any? %>
    <div class="alert alert-danger">
      <button type="button" class="close" data-dismiss="alert">×</button>
      <i class="fa fa-ban-circle"></i>
      <strong>
      有<%= @sys_user.errors.count %>条错误消息：
      </strong>
      <ul>
      <% @sys_user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <section class="panel panel-default">
    <header class="panel-heading">
      <strong>用户信息</strong>
    </header>
    <div class="panel-body">   

      <div class="form-group">
        <%=f.label :name, :required => true,:class => "col-sm-3 control-label"%>
        <div class="col-sm-6">
          <%= f.text_field :name,  
            :class => "input-sm input-s form-control parsley-validated", 
            "data-parsley-length" => "[3,20]" %> 
        </div>
      </div>
<%=params%>
      <%# 如果是新增页面才输入密码 %>
      <% if params[:action]=='new' || params[:action] == 'create'%>
        <div class="form-group">
          <%=f.label :password, :required => true,:class => "col-sm-3 control-label"%>
          <div class="col-sm-6">
            <%= f.password_field :password,
              :class => "input-sm input-s form-control parsley-validated",
              "data-parsley-minlength" => "6" %>
          </div>
        </div>

        <div class="form-group">
          <%=f.label :password_confirmation, :required => true,:class => "col-sm-3 control-label"%>
          <div class="col-sm-6">
             <%= f.password_field :password_confirmation,
                  :class => "input-sm input-s form-control parsley-validated",
                  :required => true, "data-parsley-equalto" => "#sys_user_password",
                    "data-parsley-minlength" => "6" %>
          </div>
        </div>
      <% end %>

      <div class="form-group">
        <%=f.label :email, :required => false,:class => "col-sm-3 control-label"%>
        <div class="col-sm-6">
          <%= f.text_field :email, :class => "input-sm input-s form-control parsley-validated",
              'data-parsley-type' => 'email'%> 
        </div>
      </div>

      <div class="form-group">
        <%=f.label :sex, :required => true,:class => "col-sm-3 control-label"%>
        <div class="col-sm-6">
        <%= f.input :sex,:label => false, :as => :radio_buttons, 
            :collection => [['男','0'] ,['女','1']]%>
        </div>
      </div>

      <div class="form-group">
        <%=f.label :sys_roles, :required => true,:class => "col-sm-3 control-label"%>
        <div class="col-sm-6">
        <%= f.association :sys_roles,:label => false, :as => :check_boxes, 
          label_method: :roleName, value_method: :id, include_blank: false %>
        </div>
      </div>

      <div class="form-group">
        <%=f.label :phone, :required => false,:class => "col-sm-3 control-label"%>
        <div class="col-sm-6">
          <%= f.text_field :phone, :class => "input-sm input-s form-control parsley-validated"%> 
        </div>
      </div>

      <div class="form-group">
        <%=f.label :photo, :required => false, :class => "col-sm-3 control-label"%>
        <div class="col-sm-6">
          <%= f.text_field :photo, :class => "input-sm input-s form-control parsley-validated"%> 
        </div>
      </div>
      <br/>
      <div class="form-group">
        <label class="col-sm-3 control-label"></label>
        <div class="col-sm-6">
          <%= f.button :submit, :class => "btn btn-primary", :value=> "保 存"%>&nbsp;&nbsp;&nbsp;&nbsp;
          <%= button_tag "返回", :type => 'button', :class => "btn btn-default",'onclick' => "history.go(-1)" %>
        </div>
      </div>
    </div>

    <!-- <footer class="panel-footer text-right bg-light lter"></footer> -->
  </section>

<% end %>
<script type="text/javascript">
    $('#sys_user_form').parsley();  
</script>

app/views/sys_users/edit.html.erb
<div class="m-b-md">
  <h3 class="m-b-none">修改用户</h3>
</div>
 
</div><%= render 'form' %>

app/views/sys_users/index.html.erb
<section class="panel panel-default">
    <header class="panel-heading">
      用户管理
    </header>

    <div class="row wrapper">
      <div class="col-sm-5 m-b-xs">
        <%= link_to raw('<i class="fa fa-plus"></i> 添加'), new_sys_user_path, :class => 'btn btn-sm btn-default' %>
      </div>
      <div class="col-sm-4 m-b-xs">
      </div>
      <div class="col-sm-3">
        <%= form_tag sys_users_path,:method => 'get' do -%>
          <div class="input-group">
              <%= text_field_tag :search, params[:search], :class => "input-sm form-control", :placeholder => "Search" -%>
              <span class="input-group-btn">
                <%= submit_tag "Go!", :name => nil, :class => "btn btn-sm btn-default" %>
              </span>
          </div>
        <% end %>
      </div>
    </div>

    <div class="table-responsive">
        <table class="table table-striped b-t b-light">
          <thead>
            <tr>
              <th width="120">用户名</th>
              <th>Email</th>
              <th width="100">性别</th>
              <th width="160">联系电话</th>
              <th width="220">角色</th>
              <th width="120">操作</th> 
            </tr>
          </thead>
          <tbody>
            <% @sys_users.each do |sys_user| %>
              <tr>
                <td><%= sys_user.name %></td>
                <td><%= sys_user.email %></td>
                <td><%= sys_user.sex == 1 ? '女' : '男' %></td>
                <td><%= sys_user.phone_str %></td>
                <th><%= sys_user.role_desc %></th>
                <td>
                  <div class="btn-group btn-group-sm">
                    <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
                      操 作 <span class="caret"></span>
                    </button>
                    <ul class="dropdown-menu" role="menu">
                      <li><%= link_to raw('<i class="fa fa-pencil-square"></i> 修 改'),edit_sys_user_path(sys_user) %>
                      </li>
                      <li>
                      <%= link_to raw('<i class="fa fa-minus-circle"></i> 删 除'), sys_user, method: :delete, data: { confirm: 'Are you sure?' } %>
                      
                      </li>
                    </ul>
                  </div>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>

        <footer class="panel-footer">
          <div class="row">
            <div style="float:left;padding-left:10px;">
              <%= will_paginate @sys_users,
              :page_links => true,
              :inner_window => 6,
              :outer_window => 1,
              :previous_label => '上一页',
              :next_label => '下一页'
              %>
            </div>
            <div style="float:right;padding-right:10px;height:60px;line-height:60px;">
              共找到<%= @sys_users.total_entries %>条记录, 共<%= @sys_users.total_pages %>页
            </div>
          </div>
        </footer>
    </div>
</section>
<br />

app/views/sys_users/new.html.erb
<div class="m-b-md">
  <h3 class="m-b-none">添加用户</h3>
</div>

 <%= render 'form' %>